In [1]:
import numpy
# it will compare the second value to each element in the vector
# If the values are equal, the Python interpreter returns True; otherwise, it returns False
# vector: 矢量
vector = numpy.array([5, 10, 15, 20])
vector == 10

array([False,  True, False, False])

In [2]:
matrix = numpy.array([
                    [5, 10, 15],
                    [20, 25, 30],
                    [35, 40, 45]
])
matrix == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [5]:
# Compares vector to the value 10, which generates a new Boolean vector
vector = numpy.array([5, 10, 15, 20])
equal_to_ten = (vector == 10)
print(equal_to_ten)
print(vector[equal_to_ten])
print(vector[vector==15])

[False  True False False]
[10]
[15]


In [7]:
matrix = numpy.array([
                    [5, 10, 15],
                    [20, 25, 30],
                    [35, 40, 45]
])
second_column_25 = (matrix[:, 1] == 25)
print(matrix[:, 1])
print(second_column_25)
print(matrix[second_column_25])

[10 25 40]
[False  True False]
[[20 25 30]]


In [8]:
# We can also perform comparisons with multiple 
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_and_five = (vector == 10) & (vector == 5)
print(equal_to_ten_and_five)

[False False False False]


In [9]:
# We can also perform comparisons with multiple 
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_and_five = (vector == 10) | (vector == 5)
print(equal_to_ten_and_five)

[ True  True False False]


In [12]:
# We can also perform comparisons with multiple 
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_and_five = (vector == 10) | (vector == 5)
vector[equal_to_ten_and_five] = 50
print(vector)

[50 50 15 20]


In [19]:
matrix = numpy.array([
                    [5, 10, 15],
                    [20, 25, 30],
                    [35, 40, 45]
])
second_column_25 = matrix[:, 1] == 25
print(second_column_25)
print(matrix[second_column_25])
matrix[second_column_25, 1] = 10
print(matrix)

[False  True False]
[[20 25 30]]
[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [20]:
# We can convert the data type of an array with the ndarray. astype() method.
vector = numpy.array(["1", "2", "3"])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[1. 2. 3.]


In [22]:
vector = numpy.array([5, 10, 15, 20])
vector.min()
# print(help(numpy.array))

5

In [25]:
# The axis dictates which dimension we perform the operation on
# 1 means that we want to perform the operation on each row, and 0 means on each column
matrix = numpy.array([
                    [5, 10, 15],
                    [20, 25, 30],
                    [35, 40, 45]
])
print(matrix.sum(axis=1))
print(matrix.sum(axis=0))
print(matrix.sum())

[ 30  75 120]
[60 75 90]
225


### 用pandas读取文件比numpy读取文件会更方便的多