In [1]:
import numpy as np
print(np.arange(15))
a = np.arange(15).reshape(3, 5)
a

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
# the number of axes (dimensions) of the array
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [7]:
# the total number of elements of the array
a.size

15

In [10]:
zero = np.zeros((3,4))
print(zero)
print(zero.dtype.name)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [6]:
import numpy as np
print(np.zeros(3, dtype=np.int32))

[0 0 0]


In [12]:
zero = np.zeros((3,4), dtype=np.int32)
print(zero)
print(zero.dtype.name)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [11]:
np.ones((2,3,4), dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [7]:
# To create sequences of numbers
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [9]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [8]:
np.arange(5, 50, 5).reshape(3,3)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
np.random.random((3,4))

array([[0.46084563, 0.42209839, 0.70310181, 0.84706669],
       [0.66671056, 0.90117221, 0.00741072, 0.16332631],
       [0.8369527 , 0.74515947, 0.70861829, 0.11497932]])

In [14]:
np.linspace( 5, 45, 9).reshape(3, 3)

array([[ 5., 10., 15.],
       [20., 25., 30.],
       [35., 40., 45.]])

In [12]:
from numpy import pi
np.linspace(0, 2*pi, 100)

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [20]:
np.sin(np.linspace(0, 2*pi, 100))

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [24]:
# the product operator * operates elementwise in NumPy arrays
a = np.arange(20, 60, 10)
b = np.arange(4)
print(a)
print(b)
c = a - b
print(c)
c = c - 1
print(c)
print(b**2)
print(a<35)
print(a[a<35])

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[19 28 37 46]
[0 1 4 9]
[ True  True False False]
[20 30]


In [35]:
# The matrix product can be performed using the dot function or  method
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A)
print('-------')
print(B)
print('-------')
print(A*B)
print('-------')
print(A.dot(B))
print('-------')
print(np.dot(A, B))

[[1 1]
 [0 1]]
-------
[[2 0]
 [3 4]]
-------
[[2 0]
 [0 4]]
-------
[[5 4]
 [3 4]]
-------
[[5 4]
 [3 4]]


In [36]:
import numpy as np
B = np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [37]:
# Return the floor of the input
a = np.floor(10*np.random.random((3, 4)))
print(a)
print('-------')
# a.shape
## flatten the array
print(a.ravel())
print('-------')
a.shape = (6, 2)
print(a)
print('-------')
print(a.T)


# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated
# a.reshape(3, -1)

[[8. 2. 8. 3.]
 [3. 1. 3. 3.]
 [2. 0. 9. 0.]]
-------
[8. 2. 8. 3. 3. 1. 3. 3. 2. 0. 9. 0.]
-------
[[8. 2.]
 [8. 3.]
 [3. 1.]
 [3. 3.]
 [2. 0.]
 [9. 0.]]
-------
[[8. 8. 3. 3. 2. 9.]
 [2. 3. 1. 3. 0. 0.]]


In [45]:
import numpy as np
a = np.floor(10*np.random.random((3, 3)))
b = np.floor(10*np.random.random((3, 3)))
print(a)
print('\n')
print(b)
print('\n')
print(np.vstack((a, b)))
print('\n')
print(np.hstack((a, b)))

[[1. 7. 7.]
 [0. 5. 3.]
 [8. 6. 4.]]


[[4. 4. 0.]
 [9. 4. 3.]
 [9. 8. 3.]]


[[1. 7. 7.]
 [0. 5. 3.]
 [8. 6. 4.]
 [4. 4. 0.]
 [9. 4. 3.]
 [9. 8. 3.]]


[[1. 7. 7. 4. 4. 0.]
 [0. 5. 3. 9. 4. 3.]
 [8. 6. 4. 9. 8. 3.]]


In [53]:
a = np.floor(10*np.random.random((2, 12)))
print(a)
print('\n')
print(np.hsplit(a, 3))
print('\n')
print(np.hsplit(a, (3, 4)))  # Split a after the third and the fourth column
a = np.floor(10*np.random.random((12, 2)))
print('\n')
print(a)
print(np.vsplit(a, 3))

[[4. 4. 8. 0. 3. 3. 5. 4. 7. 7. 4. 8.]
 [0. 6. 1. 1. 8. 7. 2. 7. 3. 9. 1. 2.]]


[array([[4., 4., 8., 0.],
       [0., 6., 1., 1.]]), array([[3., 3., 5., 4.],
       [8., 7., 2., 7.]]), array([[7., 7., 4., 8.],
       [3., 9., 1., 2.]])]


[array([[4., 4., 8.],
       [0., 6., 1.]]), array([[0.],
       [1.]]), array([[3., 3., 5., 4., 7., 7., 4., 8.],
       [8., 7., 2., 7., 3., 9., 1., 2.]])]


[[4. 7.]
 [4. 1.]
 [9. 5.]
 [4. 0.]
 [2. 4.]
 [6. 7.]
 [9. 4.]
 [0. 9.]
 [5. 8.]
 [8. 5.]
 [4. 1.]
 [4. 5.]]
[array([[4., 7.],
       [4., 1.],
       [9., 5.],
       [4., 0.]]), array([[2., 4.],
       [6., 7.],
       [9., 4.],
       [0., 9.]]), array([[5., 8.],
       [8., 5.],
       [4., 1.],
       [4., 5.]])]


In [57]:
# Simple assignments make no copy of array objects or of their data.
a = np.arange(12)
b = a
# a and b are two names for the same ndarray object
print(b is a)
b.shape = 3, 4
print(a.shape)
print(id(a))
print(id(b))

True
(3, 4)
1749844884016
1749844884016


In [60]:
# The view method creates a new array object that looks at the same data.
c = a.view()
print(c is a)
c.shape = 2, 6
print(a.shape)
c[0,4] = 1234
print('a:\n', a)
print('c:\n', c)
print(id(a))
print(id(c))

False
(3, 4)
a:
 [[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
c:
 [[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
1749844884016
1749844885136


In [61]:
# The copy method makes a complete copy of the array and its data.
d = a.copy()
d is a
d[0, 0] = 9999
print('d:\n', d)
print('a:\n', a)

d:
 [[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
a:
 [[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [65]:
import numpy as np
data = np.sin(np.arange(20)).reshape(5, 4)
print(data)
ind = data.argmax(axis=0)
print(ind)
data_max = data[ind, range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [68]:
a = np.arange(0, 40, 10)
print(a)
b = np.tile(a, (3, 3))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [72]:
a = np.array([[4, 3, 5], [1, 2, 1]])
print(a)
print('-------')
b = np.sort(a, axis=1)
print(b)
a.sort(axis=1)
print('-------')
print(a)
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
print(a)
print('-------')
print(j)
print('-------')
print(a[j])

[[4 3 5]
 [1 2 1]]
-------
[[3 4 5]
 [1 1 2]]
-------
[[3 4 5]
 [1 1 2]]
[4 3 1 2]
-------
[2 3 1 0]
-------
[1 2 3 4]
