## 3.1 对数值进行取整

### 问题

我们想将一个浮点数取整到固定的小数位。

### 解决方案

对于简单的取整操作，使用内建的 round(value, ndigits) 函数即可

In [1]:
round(1.23, 1)

1.2

In [2]:
round(1.27, 1)

1.3

In [3]:
round(-1.27, 1)

-1.3

In [4]:
round(1.25361, 3)

1.254

某个值恰好等于两个整数间的一半时，取整操作会取到离该值最接近的那个偶数上。

In [5]:
round(1.15, 1)

1.1

In [6]:
round(1.25, 1)

1.2

In [7]:
round(1.75, 1)

1.8

#### 补充

像 1.25，1.75 这种比较“整”一点的小数取整时会取到偶数，而 1.15 这种不“整”的小数在计算机里实际是 1.14999999*** ，因此取整时直接被四舍了。

In [8]:
a = 1627731
print(round(a, -1))
print(round(a, -2))
print(round(a, -3))

1627730
1627700
1628000


### 讨论

如果只是将数值以固定的位数输出，一般来说是用不着 round() 的

In [11]:
x = 1.23456
print(f'{x:0.2f}')
print(f'{x:0.3f}')
print(f'value is {x:0.3f}')

1.23
1.235
value is 1.235


此外，不要采用对浮点数取整的方式来“修正”精度上的问题

In [12]:
a = 2.1
b = 4.2
c = a + b
c

6.300000000000001

In [14]:
c = round(c, 1)
c

6.3

## 3.2 执行精确的小数计算

### 问题

我们需要对小数进行精确计算，不希望因为浮点数天生的误差而带来影响

### 解决方案

使用 decimal 模块

In [15]:
(2.1 + 4.2) == 6.3

False

In [16]:
from decimal import Decimal
a = Decimal('4.2')
b = Decimal('2.1')
a + b

Decimal('6.3')

In [17]:
print(a + b, type(a + b))

6.3 <class 'decimal.Decimal'>


In [18]:
(a + b) == Decimal('6.3')

True

使用 decimal 模块控制数字的位数和四舍五入

In [19]:
from decimal import localcontext
a = Decimal('1.3')
b = Decimal('1.7')
print(a / b)

0.7647058823529411764705882353


In [20]:
with localcontext() as ctx:
    ctx.prec = 3
    print(a / b)

0.765


In [21]:
with localcontext() as ctx:
    ctx.prec = 50
    print(a / b)

0.76470588235294117647058823529411764705882352941176


### 讨论

decimal 模块实现了 IBM 的通用十进制算术规范（ General Decimal Arithmetic Specification ）。  
Python 新手可能会倾向于利用 decimal 模块来规避处理 float 数据类型所固有的精度问题。但是，正确理解你的应用领域是至关重要的。  
如果我们处理的是科学或工程类的问题，像计算机图形学或者大部分带有科学性质的问题，那么更常见的做法是直接使用普通的浮点类型。  
首先，在真实世界中极少有什么东西需要计算到小数点后17位（ float 提供 17 位的精度 ）。  
因此，在计算中引入的微小误差根本就不足挂齿。  
其次，原生的浮点数运算性能要快上许多

In [23]:
nums = [1.23e+18, 1, -1.23e+18]
sum(nums)

0.0

In [25]:
import math
math.fsum(nums)

1.0

对于处理误差的算法，需要研究算法本身，并理解其误差传播（ error propagation ）的性质。

decimal 模块主要用在涉及像金融这一类业务的程序中。

## 3.3 对数值做格式化输出

### 问题

我们需要对数值做格式化输出，包括控制位数、对齐、包括千位分隔符以及其他一些细节

### 解决方案

使用 f-string 即可，[博客概览](https://blog.csdn.net/sunxb10/article/details/81036693)

In [26]:
x = 1234.56789

In [27]:
f'{x:0.2f}'

'1234.57'

In [28]:
f'{x:>10.1f}'

'    1234.6'

In [29]:
f'{x:<10.1f}'

'1234.6    '

In [30]:
f'{x:^10.1f}'

'  1234.6  '

In [32]:
f'{x:,}'

'1,234.56789'

In [33]:
f'{x:,.1f}'

'1,234.6'

In [34]:
f'{x:e}'

'1.234568e+03'

In [35]:
f'{x:0.2E}'

'1.23E+03'

### 讨论

当需要限制数值的位数时，数值会根据 round() 函数的规则来进行取整

In [38]:
a = 1.15
b = 1.25
c = 1.75
print(f'a: {a:.1f}')
print(f'b: {b:.1f}')
print(f'c: {c:.1f}')

a: 1.1
b: 1.2
c: 1.8


如果需要将加上千位分隔符的格式化操作这个需求纳入考虑，应该考察一下 local 模块中的函数。  
还可以利用字符串的 translate() 方法交换不同的分隔符。

In [40]:
swap_separators = {ord('.'): ',', ord(','): '.'}
f'{x:,}'.translate(swap_separators)

'1.234,56789'

## 3.4 同二进制、八进制和十六进制打交道

### 问题

我们需要对二以二进制、八进制或十六进制的数值做转换或输出

### 解决方案

bin()、oct() 和 hex()

In [41]:
x = 1234
bin(x)

'0b10011010010'

In [42]:
oct(x)

'0o2322'

In [43]:
hex(x)

'0x4d2'

In [44]:
f'{x:b}'

'10011010010'

In [45]:
f'{x:o}'

'2322'

In [47]:
f'{x:x}'

'4d2'

In [48]:
x = -1234
format(x, 'b')

'-10011010010'

In [49]:
format(x, 'x')

'-4d2'

In [50]:
int('4d2', 16)

1234

In [54]:
int('10011010010', 2)

1234

## 3.5 从字节串中打包和解包大整数

### 问题

我们有一个字节串，需要将其解包为一个整型数值。此外，还需要将一个大整数重新转换为一个字节串

### 解决方案

使用 int.from_bytes() 方法 和 int.to_bytes() 方法

In [56]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [57]:
len(data)

16

In [58]:
int.from_bytes(data, 'little')

69120565665751139577663547927094891008

In [59]:
int.from_bytes(data, 'big')

94522842520747284487117727783387188

In [61]:
x = 94522842520747284487117727783387188
x.to_bytes(16, 'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [62]:
x.to_bytes(16, 'little')

b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'

### 讨论

在大整数和字节串之间互相转换并不算常见的操作。  
但是，有时候在特定的应用领域中却有这样的需求，例如加密技术或网络应用中。  
比方说 IPv6 网络地址就是由一个 128 位的整数来表示的。

## 3.6 复数运算

### 问题

我们的代码在同最新的 Web 认证方案交互时遇到了奇点（singularity）问题，而唯一的解决方案是在复平面解决

### 解决方案

复数可以通过 complex(real, imag) 函数来指定，或者通过浮点数再加后缀 j 来指定

In [63]:
a = complex(2, 4)
a

(2+4j)

In [65]:
b = 3 - 5j
b

(3-5j)

In [67]:
print(f'real: {a.real}')
print(f'imag: {a.imag}')
print(f'conjugate: {a.conjugate()}')

real: 2.0
imag: 4.0
conjugate: (2-4j)


In [68]:
a + b

(5-1j)

In [69]:
a * b

(26+2j)

In [70]:
a / b

(-0.4117647058823529+0.6470588235294118j)

In [73]:
abs(3 + 4j)

5.0

如果要执行有关复数的函数操作，例如求正弦、余弦或平方根，可以使用 cmath 模块

In [74]:
import cmath
cmath.sin(a)

(24.83130584894638-11.356612711218174j)

In [75]:
cmath.cos(a)

(-11.36423470640106-24.814651485634187j)

In [76]:
cmath.exp(a)

(-4.829809383269385-5.5920560936409816j)

### 讨论

Python 中大部分和数学相关的模块都可适用于复数。例如，如果使用 numpy 模块，可以很直接地创建复数数组

In [77]:
import numpy as np
a = np.array([2 + 3j, 4 + 5j, 6 - 7j, 8 + 9j])
a

array([2.+3.j, 4.+5.j, 6.-7.j, 8.+9.j])

In [78]:
a + 2

array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j])

In [79]:
np.sin(a)

array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

Python 中的标准数学函数默认情况下不会产生复数值：

In [80]:
import math
math.sqrt(-1)

ValueError: math domain error

如果希望产生复数结果，必须明确使用 cmath 模块或者在可以感知复数的库中声明对复数类型的使用

In [81]:
import cmath
cmath.sqrt(-1)

1j

## 3.7 处理无穷大和 NaN

### 问题

我们需要对浮点数的无穷大、负无穷小或 NaN ( not a number ) 进行判断测试

### 解决方案

通过 float() 创建这些浮点数值，并用 math.isinf() 和 math.isnan() 函数检测

In [82]:
a = float('inf')
b = float('-inf')
c = float('nan')
print(f'a: {a}')
print(f'b: {b}')
print(f'c: {c}')

a: inf
b: -inf
c: nan


In [83]:
import math
math.isinf(a)

True

In [84]:
math.isnan(c)

True

In [85]:
a + 45

inf

In [86]:
a * 10

inf

In [87]:
10 / a

0.0

In [88]:
a / a

nan

In [89]:
a + b

nan

In [90]:
c + 23

nan

In [91]:
c / 2

nan

In [92]:
c * 2

nan

In [93]:
math.sqrt(c)

nan

NaN 在做比较时从不会被判定为相等：

In [94]:
c = float('nan')
d = float('nan')
c == d

False

In [95]:
c is d

False

In [96]:
# 唯一安全检测 NaN 的方法
math.isnan(d)

True

## 3.8 分数的计算

### 问题

我们突然发现自己在做涉及分数处理的小学家庭作业  
或者也许我们正在为自己的木材商店编写测量计算方面的代码

### 解决方案

fractions 模块可以用来处理涉及分数的数学计算问题

In [97]:
from fractions import Fraction
a = Fraction(5, 4)
b = Fraction(7, 16)
print(a + b)

27/16


In [98]:
print(a * b)

35/64


In [99]:
c = a * b
c.numerator

35

In [100]:
c.denominator

64

In [101]:
float(c)

0.546875

In [102]:
# Limiting the denominator of a value
print(c.limit_denominator(8))

4/7


In [103]:
# Converting a float to a fraction
x = 3.75
y = Fraction(*x.as_integer_ratio())
y

Fraction(15, 4)

## 3.9 处理大型数组的计算

### 问题

我们需要对大型的数据集比如数组或网络（ grid ）进行计算

### 解决方案

对于任何涉及数组的计算密集型任务，请使用 NumPy 库。  
NumPy 的主要特性是为 Python 提供了数组对象，比标准 Python 中的列表有着更好的性能表现，因此更加适合于做数学计算

In [1]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
print(x * 2)
print(x + y)
print(x + 10)

[1, 2, 3, 4, 1, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: can only concatenate list (not "int") to list

In [2]:
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
print(ax * 2)
print(ax + ay)
print(ax + 10)
print(ax * ay)

[2 4 6 8]
[ 6  8 10 12]
[11 12 13 14]
[ 5 12 21 32]


可以看到，NumPy 中的数组在进行标量运算时是针对逐个元素进行计算的

In [3]:
def foo(x):
    return 3 * x**2 - 2 * x + 7


foo(ax)

array([ 8, 15, 28, 47])

NumPy 提供了一些 “通用函数” 的集合，它们也能对数组进行操作。这些通用函数可作为 math 模块中所对应函数的替代。

In [4]:
np.sqrt(ax)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [5]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

使用 NumPy 中的通用函数，其效率要比对数组进行迭代然后使用 math 模块中的函数每次只处理一个元素快上**百倍**。  
因此，只要有可能就应该使用这些通用函数。

在底层，NumPy 数组的内存分配方式和 C 或者 Fortran 一样。即，它们是大块的连续内存，由同一种类型的数据组成。  
正是因为这样，NumPy 才能创建比通常 Python 中的列表要大得多的数组。  
例如，如果想创建一个 10000 \* 10000 的二维浮点数组，根本不是问题：

In [10]:
grid = np.zeros(shape=(10000, 10000), dtype=float)
print(grid)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
grid += 10
print(grid)

[[10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 ...
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]
 [10. 10. 10. ... 10. 10. 10.]]


In [12]:
np.sin(grid)

array([[-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       ...,
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111]])

NumPy 拓展了 Python 列表的索引功能

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
a[1]

array([5, 6, 7, 8])

In [15]:
a[:, 1]

array([ 2,  6, 10])

In [16]:
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [17]:
a[1:3, 1:3] += 10

In [18]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [19]:
a + [100, 101, 102, 103]

array([[101, 103, 105, 107],
       [105, 117, 119, 111],
       [109, 121, 123, 115]])

In [20]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [21]:
np.where(a < 10, a, 10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

In [22]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

### 讨论

Python 中大量的科学和工程类函数库都以 NumPy 作为基础，它也是广泛使用中的最为庞大和复杂的模块之一。

## 3.10 矩阵和线性代数的计算

### 问题

我们需要执行矩阵和线性代数方面的操作，比如矩阵乘法、求行列式、解线性方程等

### 解决方案

NumPy 库中有一个 matrix 对象可用来处理这种情况

In [24]:
import numpy as np
m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])

In [25]:
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [26]:
# Return transpose
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [27]:
# Return inverse
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [28]:
# Create a vector and multiply
v = np.matrix([[2], [3], [4]])
v

matrix([[2],
        [3],
        [4]])

In [29]:
m * v

matrix([[ 8],
        [32],
        [ 2]])

更多的操作可以在 numpy.linalg 子模块中找到：

In [30]:
import numpy.linalg as nl

# Determinant
nl.det(m)

-229.99999999999983

In [31]:
# Eigenvalues
nl.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

In [32]:
# Solve for x in mx = v
x = nl.solve(m, v)
x

matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])

In [33]:
m * x

matrix([[2.],
        [3.],
        [4.]])

In [34]:
v

matrix([[2],
        [3],
        [4]])

## 随机选择

### 问题

我们想从序列中随机挑选出元素，或者想生成随机数

### 解决方案

random 模块中有各种函数可用于需要随机数和随机选择的场景

In [35]:
import random
values = [1, 2, 3, 4, 5, 6]
random.choice(values)

4

In [36]:
random.sample(values, 2)

[5, 6]

In [37]:
random.sample(values, 3)

[5, 4, 1]

如果只是想在序列中原地打乱元素的顺序（洗牌），可以使用 random.shuffle()

In [38]:
random.shuffle(values)
values

[4, 6, 5, 2, 1, 3]

要产生随机整数，可以使用 random.randint()

In [41]:
[random.randint(0, 10) for _ in range(20)]

[7, 8, 2, 4, 5, 2, 3, 2, 1, 10, 0, 1, 5, 8, 2, 2, 5, 3, 4, 8]

要产生 0 到 1 之间均匀分布的浮点数值，可以使用 random.random()

In [43]:
[random.random() for _ in range(4)]

[0.9702874023478657,
 0.14071407696892269,
 0.1592758129721068,
 0.9946800170089819]

如果要得到由 N 个随机比特位所表示的整数，可以使用 random.getrandbits()

In [45]:
[random.getrandbits(128) for _ in range(4)]

[279233743633970853903009296518837456197,
 26418100498224602010131346090560236354,
 2229334805512322564514735901385623770,
 35221628356309703417157759018470409232]

### 讨论

`random.seed()` 函数可以修改初始的种子值。

除了以上展示的功能外，random 模块还包含有计算均匀分布、高斯分布和其它概率分布的函数。  
比如，`random.uniform()` 可以计算均匀分布值，而 `random.gauss()` 则可计算出正态分布值。

random 模块中的函数不应该用在与加密处理相关的程序中。如果需要这样的功能，考虑使用 ssl 模块中的函数来替代。

## 3.12 时间换算

### 问题

我们的代码需要进行简单的时间转换工作，比如将日转换为秒，将小时转换为分钟等

### 解决方案

我们可以利用 datetime 模块来完成不同时间单位间的换算

In [48]:
from datetime import datetime, timedelta

a = timedelta(days=2, hours=6)
b = timedelta(hours=4.5)
c = a + b
print(f'days: {c.days}')
print(f'seconds: {c.seconds}')
print(f'hours: {c.seconds/3600}')
print(f'total_hours: {c.total_seconds()/3600}')

days: 2
seconds: 37800
hours: 10.5
total_hours: 58.5


In [49]:
a = datetime(2019, 4, 4)
print(a + timedelta(days=10))

2019-04-14 00:00:00


In [50]:
b = datetime(2019, 7, 1)
d = b - a
d.days

88

In [51]:
now = datetime.today()
print(f'now: {now}')
print(f'10 minutes later: {now + timedelta(minutes=10)}')

now: 2019-04-04 13:28:40.600331
10 minutes later: 2019-04-04 13:38:40.600331


### 讨论

大部分基本的日期和时间操控问题，datetime 模块已足够满足要求了。如果需要处理更为复杂的日期问题，比如处理时区、模糊时间范围、计算节日的日期等，可以试试 dateutil 模块。

dateutil 的一个显著特点是在处理有关月份的问题时能填补一些 datetime 模块留下的空缺。

In [52]:
a = datetime(2019, 4, 4)
a + timedelta(months=1)

TypeError: 'months' is an invalid keyword argument for __new__()

In [56]:
from dateutil.relativedelta import relativedelta

t = datetime(2019, 1, 31)
t + relativedelta(months=+1)

datetime.datetime(2019, 2, 28, 0, 0)

In [57]:
t + relativedelta(months=+3)

datetime.datetime(2019, 4, 30, 0, 0)

In [58]:
r = datetime(2019, 7, 1)
d = r - t
d

datetime.timedelta(days=151)

In [59]:
d = relativedelta(r, t)
d

relativedelta(months=+5, days=+1)

In [60]:
d.months

5

In [61]:
d.days

1

## 3.13 计算上周5的日期

### 问题

我们希望有一个通用的解决方案能找出一周中上一次出现某天时的日期。比方说上周五是几月几号？

### 解决方案

Python 的 datetime 模块中有一些实用函数和类可以帮助我们完成这样的计算

In [62]:
from datetime import datetime, timedelta

weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

def get_previous_byday(dayname, start_date=None):
    if start_date is None:
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = (7 + day_num - day_num_target) % 7
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days=days_ago)
    return target_date

In [63]:
get_previous_byday('Monday')

datetime.datetime(2019, 4, 1, 13, 43, 48, 975894)

In [64]:
get_previous_byday('Thursday')

datetime.datetime(2019, 3, 28, 13, 45, 53, 532272)

In [66]:
get_previous_byday('Friday', datetime(2019, 7, 1))

datetime.datetime(2019, 6, 28, 0, 0)

### 讨论

如果需要执行大量类似的日期计算，最好安装 python-dateutil 包。例如，下面这个例子是使用 dateutil 模块中的 `relativedelta()` 函数来执行同样的计算：

In [67]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
from dateutil.rrule import *

d = datetime.now()
print(d)

2019-04-04 13:48:52.830192


In [68]:
# Next Friday
print(d + relativedelta(weekday=FR))

2019-04-05 13:48:52.830192


In [69]:
# Last Friday
print(d + relativedelta(weekday=FR(-1)))

2019-03-29 13:48:52.830192


## 3.14 找出当月的日期范围

### 问题

我们有一些代码需要循环迭代当月中的每个日期，我们需要一种高效的方法来计算出日期的范围

### 解决方案

计算出范围的开始和结束日期，然后在迭代时利用 datetime.timedelta 对象来递增日期

In [71]:
from datetime import datetime, date, timedelta
import calendar

def get_month_range(start_date=None):
    if start_date is None:
        start_date = datetime.today().replace(day=1)
    _, days_in_month = calendar.monthrange(start_date.year, start_date.month)
    end_date = start_date + timedelta(days=days_in_month)
    return (start_date, end_date)

In [73]:
a_day = timedelta(days=1)
first_day, last_day = get_month_range()

In [74]:
while first_day < last_day:
    print(first_day)
    first_day += a_day

2019-04-01 13:54:30.720583
2019-04-02 13:54:30.720583
2019-04-03 13:54:30.720583
2019-04-04 13:54:30.720583
2019-04-05 13:54:30.720583
2019-04-06 13:54:30.720583
2019-04-07 13:54:30.720583
2019-04-08 13:54:30.720583
2019-04-09 13:54:30.720583
2019-04-10 13:54:30.720583
2019-04-11 13:54:30.720583
2019-04-12 13:54:30.720583
2019-04-13 13:54:30.720583
2019-04-14 13:54:30.720583
2019-04-15 13:54:30.720583
2019-04-16 13:54:30.720583
2019-04-17 13:54:30.720583
2019-04-18 13:54:30.720583
2019-04-19 13:54:30.720583
2019-04-20 13:54:30.720583
2019-04-21 13:54:30.720583
2019-04-22 13:54:30.720583
2019-04-23 13:54:30.720583
2019-04-24 13:54:30.720583
2019-04-25 13:54:30.720583
2019-04-26 13:54:30.720583
2019-04-27 13:54:30.720583
2019-04-28 13:54:30.720583
2019-04-29 13:54:30.720583
2019-04-30 13:54:30.720583


### 讨论

**日期和时间可以通过标准的算术和比较操作符来进行操作。**

最理想的方法是创建一个专门处理日期的函数，而且用法和 Python 内建的 range() 一样。

In [81]:
def date_range(start, stop, step):
    while start < stop:
        yield start
        start += step

for d in date_range(datetime(2020, 2, 1), datetime(2020, 3, 1), timedelta(hours=12)):
    print(d)

2020-02-01 00:00:00
2020-02-01 12:00:00
2020-02-02 00:00:00
2020-02-02 12:00:00
2020-02-03 00:00:00
2020-02-03 12:00:00
2020-02-04 00:00:00
2020-02-04 12:00:00
2020-02-05 00:00:00
2020-02-05 12:00:00
2020-02-06 00:00:00
2020-02-06 12:00:00
2020-02-07 00:00:00
2020-02-07 12:00:00
2020-02-08 00:00:00
2020-02-08 12:00:00
2020-02-09 00:00:00
2020-02-09 12:00:00
2020-02-10 00:00:00
2020-02-10 12:00:00
2020-02-11 00:00:00
2020-02-11 12:00:00
2020-02-12 00:00:00
2020-02-12 12:00:00
2020-02-13 00:00:00
2020-02-13 12:00:00
2020-02-14 00:00:00
2020-02-14 12:00:00
2020-02-15 00:00:00
2020-02-15 12:00:00
2020-02-16 00:00:00
2020-02-16 12:00:00
2020-02-17 00:00:00
2020-02-17 12:00:00
2020-02-18 00:00:00
2020-02-18 12:00:00
2020-02-19 00:00:00
2020-02-19 12:00:00
2020-02-20 00:00:00
2020-02-20 12:00:00
2020-02-21 00:00:00
2020-02-21 12:00:00
2020-02-22 00:00:00
2020-02-22 12:00:00
2020-02-23 00:00:00
2020-02-23 12:00:00
2020-02-24 00:00:00
2020-02-24 12:00:00
2020-02-25 00:00:00
2020-02-25 12:00:00


## 将字符串转换为日期

### 问题

我们的应用程序接收到字符串形式的临时数据，但是我们想将这些字符串转换为 datetime 对象，以此对它们执行一些非字符串的操作

### 解决方案

datetime 模块是用来处理这种问题的简单方案，但是 strptime() 方法的性能非常糟糕

In [86]:
from datetime import datetime
text = '2019-04-01'
y = datetime.strptime(text, '%Y-%m-%d')
z = datetime.now()
print(y)
diff = z - y
diff

2019-04-01 00:00:00


datetime.timedelta(days=3, seconds=57507, microseconds=345124)

In [84]:
z

datetime.datetime(2019, 4, 4, 15, 57, 44, 160602)

In [87]:
nice_z = datetime.strftime(z, '%A %B %d, %Y')
nice_z

'Thursday April 04, 2019'

In [88]:
def parse_ymd(s):
    year_s, mon_s, day_s = s.split('-')
    return datetime(int(year_s), int(mon_s), int(day_s))

In [91]:
timeit parse_ymd(text)

1.46 µs ± 4.28 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [92]:
timeit datetime.strptime(text, '%Y-%m-%d')

11 µs ± 104 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


可见， `parse_ymd(s)` 比 `datetime.strptime()` **快了 7 倍多**

## 3.16 处理涉及到时区的日期问题

### 问题

我们有一个电话会议定在芝加哥时间 2012 年 12 月 21 日上午 9:30 举行。那么在印度班加罗尔的朋友应该在当地时间几点出现才能赶上会议？

### 解决方案

对于几乎任何涉及时区的问题，都应该使用 pytz 模块来解决。这个 Python 包提供了奥尔森时区数据库

In [98]:
from datetime import datetime, timedelta
from pytz import timezone

d = datetime(2012, 12, 21, 9, 30, 0)
print(d)

2012-12-21 09:30:00


In [94]:
# Localize the date for Chicago
central = timezone('US/Central')
loc_d = central.localize(d)
print(loc_d)

2012-12-21 09:30:00-06:00


In [95]:
# Convert to Bangalore time
bang_d = loc_d.astimezone(timezone('Asia/Kolkata'))
print(bang_d)

2012-12-21 21:00:00+05:30


如果打算对本地化的日期做算术计算，需要特别注意夏令时转换和其他方面的细节。  
比如，2013年美国的标准夏令时于本地时间 3 月 13 日凌晨 2 点开始（此时时间要往前拨一小时）。如果直接进行算术计算就会得到错误的结果。

In [99]:
d = datetime(2013, 3, 10, 1, 45)
loc_d = central.localize(d)
print(loc_d)

2013-03-10 01:45:00-06:00


In [100]:
later = loc_d + timedelta(minutes=30)
print(later)

2013-03-10 02:15:00-06:00


结果是错误的，因为上面的代码没有把本地时间中跳过的 1 小时给算上。要解决这个问题，可以使用 timezone 对象的 normalize() 方法。

In [101]:
later = central.normalize(loc_d + timedelta(minutes=30))
print(later)

2013-03-10 03:15:00-05:00


### 讨论

为了不让我们的头炸掉，通常用来处理本地时间的方法是将所有的日期都转换为 UTC （世界统一时间）时间，然后在所有的内部存储和处理中都使用 UTC 时间。

In [102]:
print(loc_d)

2013-03-10 01:45:00-06:00


In [104]:
import pytz

utc_d = loc_d.astimezone(pytz.utc)
print(utc_d)

2013-03-10 07:45:00+00:00


In [105]:
later_utc = utc_d + timedelta(minutes=30)
print(later_utc.astimezone(central))

2013-03-10 03:15:00-05:00


要找出时区名称，可以考察一下 pytz.country_timezones，这是一个字典，可以使用 ISO 3166 国家代码作为 key 来查询。

In [107]:
pytz.country_timezones['IN']

['Asia/Kolkata']